spring.application.name=papertrail

# Dynamic Database Configuration (Reads from Render environment variables in the cloud, falls back to your PC locally)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/papertrail}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Anusaya@1228}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Bumps the limits up to 200MB to comfortably support massive scanned notebook PDFs
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# Allows Tomcat to accept large form payloads without cutting off the stream
server.tomcat.max-http-form-post-size=200MB